Repository AY2122S2-CS2103-F11-4/tp, pull requests merged in 2022-03, with the labels that each got.

#26 Add "add task" command
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/TaskList.java
  src/main/java/seedu/address/model/task/Task.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
Labels: type.Enhancement, priority.High

#37 Update UG, DG and PPP
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/putaojuice.md
Labels: type.Documentation

#38 Update UG, DG and PPP based on implementation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/yumengtan.md
Labels: type.Documentation

#63 Improvements v1.3
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/diagrams/DeleteTaskActivityDiagram.puml
  docs/diagrams/DeleteTaskSequenceDiagram.puml
  docs/images/DeleteTaskActivityDiagram.png
  docs/images/DeleteTaskSequenceDiagram.png
  docs/team/ivorcmx.md
Labels: type.Documentation

#68 Add update task command and its parser
  src/main/java/seedu/address/logic/commands/UpdateTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/UpdateTaskCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/TaskList.java
  src/main/java/seedu/address/model/task/Task.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/FindTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewTaskCommandTest.java
Labels: priority.High

#74 TaskList Storage
  README.md
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/index.md
  docs/team/yumengtan.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyTaskList.java
  src/main/java/seedu/address/model/TaskList.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/storage/JsonSerializableTaskList.java
  src/main/java/seedu/address/storage/JsonTaskListStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/TaskListStorage.java
  src/test/data/JsonSerializableTaskListTest/invalidTaskTaskList.json
  src/test/data/JsonSerializableTaskListTest/typicalTaskTaskList.json
  src/test/data/JsonTaskListStorageTest/invalidAndValidTaskTaskList.json
  src/test/data/JsonTaskListStorageTest/invalidTaskTaskList.json
  src/test/data/JsonTaskListStorageTest/notJsonFormatAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/FindTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewTaskCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/TaskListTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/address/storage/JsonSerializableTaskListTest.java
  src/test/java/seedu/address/storage/JsonTaskListStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/TypicalTask.java
Labels: priority.High

#78 Update Ui to show TaskList in Gui
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/TaskList.java
  src/main/java/seedu/address/model/task/UniqueTaskList.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/java/seedu/address/ui/TaskListPanel.java
  src/main/resources/images/NUScheduler_32.png
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TaskCard.fxml
  src/main/resources/view/TaskListPanel.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/FindTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/UpdateTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewTaskCommandTest.java
Labels: priority.High

#80 Documentation v1.3
  docs/UserGuide.md
  docs/team/putaojuice.md
Labels: type.Documentation
